
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
				
#ifndef UIB_FINEDUST_VIEW_VIEW_H_
#define UIB_FINEDUST_VIEW_VIEW_H_


#include "g_inc_uib.h"
#include "uib_views.h"

/**
* view context definitions
*/

typedef struct _uib_finedust_view_view_context {

	/* parent evas_object which was parameter of create function */
	Evas_Object *parent;
	/* root container UI Component of this view */
	Evas_Object *root_container;
	/* view class name */
	const char *view_name;
	/* indicator state of this view */
	int indicator_state;
	/* This is view type. 'true' is user view, otherwise a UI Builder's view. */
	bool is_user_view;
	/* control context to control this view */
	struct _uib_finedust_view_control_context *cc;

	/* UI Components in this view */
	Evas_Object *finedust_grid;
	Evas_Object *fdv_previous_button;
	Evas_Object *finedust_box;
	Evas_Object *fdb_grid;
	Evas_Object *fdg_outdoor_button;
	Evas_Object *fdg_outdoor_box;
	Evas_Object *outdoor_label;
	Evas_Object *fdg_indoor_button;
	Evas_Object *fdg_indoor_box;
	Evas_Object *indoor_label;
	Evas_Object *fdg_icon_button;
	Evas_Object *fdg_icon_box;
	Evas_Object *icon_label;
	Evas_Object *fdv_next_button;
} uib_finedust_view_view_context;



/**
* @brief	Create a new view then return view context of that view.
* 			You can delete view using evas_object_del(vc->evas_object) like other EFL evas objects.
*/
uib_view_context *uib_view_finedust_view_create(Evas_Object *parent, void *create_callback_param);
uib_view_context *uib_view_finedust_view_destroy(Evas_Object *parent, void *create_callback_param);

void uib_finedust_view_config_HD_portrait();
void finedust_view_fdv_previous_button_onclicked(uib_finedust_view_view_context *vc, Evas_Object *obj, void *event_info);
void finedust_view_fdv_previous_button_onclicked_post(void* param, uib_finedust_view_view_context *vc, Evas_Object *obj, void *event_info);
void finedust_view_fdv_next_button_onclicked(uib_finedust_view_view_context *vc, Evas_Object *obj, void *event_info);
void finedust_view_fdv_next_button_onclicked_post(void* param, uib_finedust_view_view_context *vc, Evas_Object *obj, void *event_info);
#endif /* UIB_FINEDUST_VIEW_VIEW_H_ */
