
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
				
#ifndef UIB_DATETIME_VIEW_VIEW_H_
#define UIB_DATETIME_VIEW_VIEW_H_


#include "g_inc_uib.h"
#include "uib_views.h"

/**
* view context definitions
*/

typedef struct _uib_datetime_view_view_context {

	/* parent evas_object which was parameter of create function */
	Evas_Object *parent;
	/* root container UI Component of this view */
	Evas_Object *root_container;
	/* view class name */
	const char *view_name;
	/* indicator state of this view */
	int indicator_state;
	/* This is view type. 'true' is user view, otherwise a UI Builder's view. */
	bool is_user_view;
	/* control context to control this view */
	struct _uib_datetime_view_control_context *cc;

	/* UI Components in this view */
	Evas_Object *datetime_grid;
	Evas_Object *dtv_previous_button;
	Evas_Object *datetime_box;
	Evas_Object *dtb_grid;
	Evas_Object *ftg_time_button;
	Evas_Object *dtg_time_box;
	Evas_Object *time_label;
	Evas_Object *ftg_date_button;
	Evas_Object *dtg_date_box;
	Evas_Object *date_label;
	Evas_Object *dtv_next_button;
} uib_datetime_view_view_context;



/**
* @brief	Create a new view then return view context of that view.
* 			You can delete view using evas_object_del(vc->evas_object) like other EFL evas objects.
*/
uib_view_context *uib_view_datetime_view_create(Evas_Object *parent, void *create_callback_param);
uib_view_context *uib_view_datetime_view_destroy(Evas_Object *parent, void *create_callback_param);

void uib_datetime_view_config_HD_portrait();
void datetime_view_dtv_previous_button_onclicked(uib_datetime_view_view_context *vc, Evas_Object *obj, void *event_info);
void datetime_view_dtv_previous_button_onclicked_post(void* param, uib_datetime_view_view_context *vc, Evas_Object *obj, void *event_info);
void datetime_view_dtv_next_button_onclicked(uib_datetime_view_view_context *vc, Evas_Object *obj, void *event_info);
void datetime_view_dtv_next_button_onclicked_post(void* param, uib_datetime_view_view_context *vc, Evas_Object *obj, void *event_info);
#endif /* UIB_DATETIME_VIEW_VIEW_H_ */
