
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"


/* event handler declarations */
void connection_deskstatus_view_dsv_previous_button_onclicked(uib_deskstatus_view_view_context*, Evas_Object*, void*);
void deskstatus_view_dsg_away_button_onclicked(uib_deskstatus_view_view_context*, Evas_Object*, void*);
void deskstatus_view_dsg_trip_button_onclicked(uib_deskstatus_view_view_context*, Evas_Object*, void*);
void connection_deskstatus_view_dsv_next_button_onclicked(uib_deskstatus_view_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_deskstatus_view_create(Evas_Object* parent, void* create_callback_param) {
	uib_deskstatus_view_view_context* vc = calloc(1, sizeof(uib_deskstatus_view_view_context));
	vc->parent = parent;
	vc->view_name = "deskstatus_view";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->deskstatus_grid) {
		vc->deskstatus_grid= elm_grid_add(parent);
		vc->root_container = vc->deskstatus_grid;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler
	evas_object_smart_callback_add(vc->dsv_previous_button, "clicked", (Evas_Smart_Cb)connection_deskstatus_view_dsv_previous_button_onclicked, vc);

	evas_object_smart_callback_add(vc->dsg_away_button, "clicked", (Evas_Smart_Cb)deskstatus_view_dsg_away_button_onclicked, vc);
	evas_object_smart_callback_add(vc->dsg_trip_button, "clicked", (Evas_Smart_Cb)deskstatus_view_dsg_trip_button_onclicked, vc);
	evas_object_smart_callback_add(vc->dsv_next_button, "clicked", (Evas_Smart_Cb)connection_deskstatus_view_dsv_next_button_onclicked, vc);



	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_deskstatus_view_config_HD_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_deskstatus_view_view_context* vc = (uib_deskstatus_view_view_context*)uib_app_manager->find_view_context("deskstatus_view");
	if(!vc) {
		return;
	}
	if(vc->deskstatus_grid) {
		elm_grid_clear(vc->deskstatus_grid, EINA_FALSE);
		evas_object_size_hint_align_set(vc->deskstatus_grid, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->deskstatus_grid, 1.0, 1.0);		elm_grid_size_set(vc->deskstatus_grid, 1000, 1000);
		if (!vc->dsv_previous_button) {
			vc->dsv_previous_button = elm_button_add(vc->deskstatus_grid);
		}
		if (vc->dsv_previous_button) {
			evas_object_size_hint_align_set(vc->dsv_previous_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->dsv_previous_button, 1.0, 1.0);			elm_object_text_set(vc->dsv_previous_button,_UIB_LOCALE("미세먼지"));
			elm_object_style_set(vc->dsv_previous_button,"bottom");
			evas_object_show(vc->dsv_previous_button);
		}
		if (!vc->deskstatus_box) {
			vc->deskstatus_box = elm_box_add(vc->deskstatus_grid);
		}
		if(vc->deskstatus_box) {
			elm_win_alpha_set(vc->deskstatus_box, EINA_FALSE);
			elm_box_homogeneous_set(vc->deskstatus_box, EINA_FALSE);
			elm_box_horizontal_set(vc->deskstatus_box, EINA_FALSE);
			elm_box_padding_set(vc->deskstatus_box,0,0);
			evas_object_size_hint_align_set(vc->deskstatus_box, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->deskstatus_box, 1.0, 1.0);
			if (!vc->dsb_grid) {
				vc->dsb_grid= elm_grid_add(vc->deskstatus_box);
			}
			if(vc->dsb_grid) {
				elm_grid_clear(vc->dsb_grid, EINA_FALSE);
				evas_object_size_hint_align_set(vc->dsb_grid, -1.0, -1.0);				evas_object_size_hint_weight_set(vc->dsb_grid, 1.0, 1.0);				elm_grid_size_set(vc->dsb_grid, 1000, 1000);
				if (!vc->dsg_away_button) {
					vc->dsg_away_button = elm_button_add(vc->dsb_grid);
				}
				if (vc->dsg_away_button) {
					evas_object_size_hint_align_set(vc->dsg_away_button, -1.0, -1.0);					evas_object_size_hint_weight_set(vc->dsg_away_button, 1.0, 1.0);					elm_object_text_set(vc->dsg_away_button,_UIB_LOCALE("자리비움"));
					elm_object_style_set(vc->dsg_away_button,"bottom");
					evas_object_show(vc->dsg_away_button);
				}
				if (!vc->dsg_away_box) {
					vc->dsg_away_box = elm_box_add(vc->dsb_grid);
				}
				if(vc->dsg_away_box) {
					elm_win_alpha_set(vc->dsg_away_box, EINA_FALSE);
					elm_box_homogeneous_set(vc->dsg_away_box, EINA_FALSE);
					elm_box_horizontal_set(vc->dsg_away_box, EINA_FALSE);
					elm_box_padding_set(vc->dsg_away_box,0,0);
					evas_object_size_hint_align_set(vc->dsg_away_box, -1.0, -1.0);
					evas_object_size_hint_weight_set(vc->dsg_away_box, 1.0, 1.0);
					if (!vc->away_label) {
						vc->away_label = elm_label_add(vc->dsg_away_box);
					}
					if(vc->away_label) {
						elm_object_text_set(vc->away_label,_UIB_LOCALE("자리비움"));
						evas_object_show(vc->away_label);
					}
					elm_box_pack_end(vc->dsg_away_box, vc->away_label);
					evas_object_show(vc->dsg_away_box);
				}
				if (!vc->dsg_trip_button) {
					vc->dsg_trip_button = elm_button_add(vc->dsb_grid);
				}
				if (vc->dsg_trip_button) {
					evas_object_size_hint_align_set(vc->dsg_trip_button, -1.0, -1.0);					evas_object_size_hint_weight_set(vc->dsg_trip_button, 1.0, 1.0);					elm_object_text_set(vc->dsg_trip_button,_UIB_LOCALE("출장중"));
					elm_object_style_set(vc->dsg_trip_button,"bottom");
					evas_object_show(vc->dsg_trip_button);
				}
				if (!vc->dsg_trip_box) {
					vc->dsg_trip_box = elm_box_add(vc->dsb_grid);
				}
				if(vc->dsg_trip_box) {
					elm_win_alpha_set(vc->dsg_trip_box, EINA_FALSE);
					elm_box_homogeneous_set(vc->dsg_trip_box, EINA_FALSE);
					elm_box_horizontal_set(vc->dsg_trip_box, EINA_FALSE);
					elm_box_padding_set(vc->dsg_trip_box,0,0);
					evas_object_size_hint_align_set(vc->dsg_trip_box, -1.0, -1.0);
					evas_object_size_hint_weight_set(vc->dsg_trip_box, 1.0, 1.0);
					if (!vc->trip_label) {
						vc->trip_label = elm_label_add(vc->dsg_trip_box);
					}
					if(vc->trip_label) {
						elm_object_text_set(vc->trip_label,_UIB_LOCALE("출장중"));
						evas_object_show(vc->trip_label);
					}
					elm_box_pack_end(vc->dsg_trip_box, vc->trip_label);
					evas_object_hide(vc->dsg_trip_box);
				}
				elm_grid_pack(vc->dsb_grid, vc->dsg_away_button, 0, 0, 500, 140);				elm_grid_pack(vc->dsb_grid, vc->dsg_away_box, 0, 140, 1000, 860);				elm_grid_pack(vc->dsb_grid, vc->dsg_trip_button, 500, 0, 500, 140);				elm_grid_pack(vc->dsb_grid, vc->dsg_trip_box, 0, 140, 1000, 860);				evas_object_show(vc->dsb_grid);
			}
			elm_box_pack_end(vc->deskstatus_box, vc->dsb_grid);
			evas_object_show(vc->deskstatus_box);
		}
		if (!vc->dsv_next_button) {
			vc->dsv_next_button = elm_button_add(vc->deskstatus_grid);
		}
		if (vc->dsv_next_button) {
			evas_object_size_hint_align_set(vc->dsv_next_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->dsv_next_button, 1.0, 1.0);			elm_object_text_set(vc->dsv_next_button,_UIB_LOCALE("날짜시간"));
			elm_object_style_set(vc->dsv_next_button,"bottom");
			evas_object_show(vc->dsv_next_button);
		}
		elm_grid_pack(vc->deskstatus_grid, vc->dsv_previous_button, 100, 100, 800, 80);		elm_grid_pack(vc->deskstatus_grid, vc->deskstatus_box, 0, 265, 1000, 435);		elm_grid_pack(vc->deskstatus_grid, vc->dsv_next_button, 100, 850, 800, 80);		evas_object_show(vc->deskstatus_grid);
	}
}

