
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"


/* event handler declarations */
void connection_finedust_view_fdv_previous_button_onclicked(uib_finedust_view_view_context*, Evas_Object*, void*);
void finedust_view_fdg_outdoor_button_onclicked(uib_finedust_view_view_context*, Evas_Object*, void*);
void finedust_view_fdg_indoor_button_onclicked(uib_finedust_view_view_context*, Evas_Object*, void*);
void finedust_view_fdg_icon_button_onclicked(uib_finedust_view_view_context*, Evas_Object*, void*);
void connection_finedust_view_fdv_next_button_onclicked(uib_finedust_view_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_finedust_view_create(Evas_Object* parent, void* create_callback_param) {
	uib_finedust_view_view_context* vc = calloc(1, sizeof(uib_finedust_view_view_context));
	vc->parent = parent;
	vc->view_name = "finedust_view";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->finedust_grid) {
		vc->finedust_grid= elm_grid_add(parent);
		vc->root_container = vc->finedust_grid;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler
	evas_object_smart_callback_add(vc->fdv_previous_button, "clicked", (Evas_Smart_Cb)connection_finedust_view_fdv_previous_button_onclicked, vc);

	evas_object_smart_callback_add(vc->fdg_outdoor_button, "clicked", (Evas_Smart_Cb)finedust_view_fdg_outdoor_button_onclicked, vc);
	evas_object_smart_callback_add(vc->fdg_indoor_button, "clicked", (Evas_Smart_Cb)finedust_view_fdg_indoor_button_onclicked, vc);
	evas_object_smart_callback_add(vc->fdg_icon_button, "clicked", (Evas_Smart_Cb)finedust_view_fdg_icon_button_onclicked, vc);
	evas_object_smart_callback_add(vc->fdv_next_button, "clicked", (Evas_Smart_Cb)connection_finedust_view_fdv_next_button_onclicked, vc);



	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_finedust_view_config_HD_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_finedust_view_view_context* vc = (uib_finedust_view_view_context*)uib_app_manager->find_view_context("finedust_view");
	if(!vc) {
		return;
	}
	if(vc->finedust_grid) {
		elm_grid_clear(vc->finedust_grid, EINA_FALSE);
		evas_object_size_hint_align_set(vc->finedust_grid, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->finedust_grid, 1.0, 1.0);		elm_grid_size_set(vc->finedust_grid, 1000, 1000);
		if (!vc->fdv_previous_button) {
			vc->fdv_previous_button = elm_button_add(vc->finedust_grid);
		}
		if (vc->fdv_previous_button) {
			evas_object_size_hint_align_set(vc->fdv_previous_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->fdv_previous_button, 1.0, 1.0);			elm_object_text_set(vc->fdv_previous_button,_UIB_LOCALE("날짜시간"));
			elm_object_style_set(vc->fdv_previous_button,"bottom");
			evas_object_show(vc->fdv_previous_button);
		}
		if (!vc->finedust_box) {
			vc->finedust_box = elm_box_add(vc->finedust_grid);
		}
		if(vc->finedust_box) {
			elm_win_alpha_set(vc->finedust_box, EINA_FALSE);
			elm_box_homogeneous_set(vc->finedust_box, EINA_FALSE);
			elm_box_horizontal_set(vc->finedust_box, EINA_FALSE);
			elm_box_padding_set(vc->finedust_box,0,0);
			evas_object_size_hint_align_set(vc->finedust_box, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->finedust_box, 1.0, 1.0);
			if (!vc->fdb_grid) {
				vc->fdb_grid= elm_grid_add(vc->finedust_box);
			}
			if(vc->fdb_grid) {
				elm_grid_clear(vc->fdb_grid, EINA_FALSE);
				evas_object_size_hint_align_set(vc->fdb_grid, -1.0, -1.0);				evas_object_size_hint_weight_set(vc->fdb_grid, 1.0, 1.0);				elm_grid_size_set(vc->fdb_grid, 1000, 1000);
				if (!vc->fdg_outdoor_button) {
					vc->fdg_outdoor_button = elm_button_add(vc->fdb_grid);
				}
				if (vc->fdg_outdoor_button) {
					evas_object_size_hint_align_set(vc->fdg_outdoor_button, -1.0, -1.0);					evas_object_size_hint_weight_set(vc->fdg_outdoor_button, 1.0, 1.0);					elm_object_text_set(vc->fdg_outdoor_button,_UIB_LOCALE("실외"));
					elm_object_style_set(vc->fdg_outdoor_button,"bottom");
					evas_object_show(vc->fdg_outdoor_button);
				}
				if (!vc->fdg_outdoor_box) {
					vc->fdg_outdoor_box = elm_box_add(vc->fdb_grid);
				}
				if(vc->fdg_outdoor_box) {
					elm_win_alpha_set(vc->fdg_outdoor_box, EINA_FALSE);
					elm_box_homogeneous_set(vc->fdg_outdoor_box, EINA_FALSE);
					elm_box_horizontal_set(vc->fdg_outdoor_box, EINA_FALSE);
					elm_box_padding_set(vc->fdg_outdoor_box,0,0);
					evas_object_size_hint_align_set(vc->fdg_outdoor_box, -1.0, -1.0);
					evas_object_size_hint_weight_set(vc->fdg_outdoor_box, 1.0, 1.0);
					if (!vc->outdoor_label) {
						vc->outdoor_label = elm_label_add(vc->fdg_outdoor_box);
					}
					if(vc->outdoor_label) {
						elm_object_text_set(vc->outdoor_label,_UIB_LOCALE("실외"));
						evas_object_show(vc->outdoor_label);
					}
					elm_box_pack_end(vc->fdg_outdoor_box, vc->outdoor_label);
					evas_object_hide(vc->fdg_outdoor_box);
				}
				if (!vc->fdg_indoor_button) {
					vc->fdg_indoor_button = elm_button_add(vc->fdb_grid);
				}
				if (vc->fdg_indoor_button) {
					evas_object_size_hint_align_set(vc->fdg_indoor_button, -1.0, -1.0);					evas_object_size_hint_weight_set(vc->fdg_indoor_button, 1.0, 1.0);					elm_object_text_set(vc->fdg_indoor_button,_UIB_LOCALE("실내"));
					elm_object_style_set(vc->fdg_indoor_button,"bottom");
					evas_object_show(vc->fdg_indoor_button);
				}
				if (!vc->fdg_indoor_box) {
					vc->fdg_indoor_box = elm_box_add(vc->fdb_grid);
				}
				if(vc->fdg_indoor_box) {
					elm_win_alpha_set(vc->fdg_indoor_box, EINA_FALSE);
					elm_box_homogeneous_set(vc->fdg_indoor_box, EINA_FALSE);
					elm_box_horizontal_set(vc->fdg_indoor_box, EINA_FALSE);
					elm_box_padding_set(vc->fdg_indoor_box,0,0);
					evas_object_size_hint_align_set(vc->fdg_indoor_box, -1.0, -1.0);
					evas_object_size_hint_weight_set(vc->fdg_indoor_box, 1.0, 1.0);
					if (!vc->indoor_label) {
						vc->indoor_label = elm_label_add(vc->fdg_indoor_box);
					}
					if(vc->indoor_label) {
						elm_object_text_set(vc->indoor_label,_UIB_LOCALE("실내"));
						evas_object_show(vc->indoor_label);
					}
					elm_box_pack_end(vc->fdg_indoor_box, vc->indoor_label);
					evas_object_show(vc->fdg_indoor_box);
				}
				if (!vc->fdg_icon_button) {
					vc->fdg_icon_button = elm_button_add(vc->fdb_grid);
				}
				if (vc->fdg_icon_button) {
					evas_object_size_hint_align_set(vc->fdg_icon_button, -1.0, -1.0);					evas_object_size_hint_weight_set(vc->fdg_icon_button, 1.0, 1.0);					elm_object_text_set(vc->fdg_icon_button,_UIB_LOCALE("아이콘"));
					elm_object_style_set(vc->fdg_icon_button,"bottom");
					evas_object_show(vc->fdg_icon_button);
				}
				if (!vc->fdg_icon_box) {
					vc->fdg_icon_box = elm_box_add(vc->fdb_grid);
				}
				if(vc->fdg_icon_box) {
					elm_win_alpha_set(vc->fdg_icon_box, EINA_FALSE);
					elm_box_homogeneous_set(vc->fdg_icon_box, EINA_FALSE);
					elm_box_horizontal_set(vc->fdg_icon_box, EINA_FALSE);
					elm_box_padding_set(vc->fdg_icon_box,0,0);
					evas_object_size_hint_align_set(vc->fdg_icon_box, -1.0, -1.0);
					evas_object_size_hint_weight_set(vc->fdg_icon_box, 1.0, 1.0);
					if (!vc->icon_label) {
						vc->icon_label = elm_label_add(vc->fdg_icon_box);
					}
					if(vc->icon_label) {
						elm_object_text_set(vc->icon_label,_UIB_LOCALE("아이콘"));
						evas_object_show(vc->icon_label);
					}
					elm_box_pack_end(vc->fdg_icon_box, vc->icon_label);
					evas_object_hide(vc->fdg_icon_box);
				}
				elm_grid_pack(vc->fdb_grid, vc->fdg_outdoor_button, 0, 0, 333, 140);				elm_grid_pack(vc->fdb_grid, vc->fdg_outdoor_box, 0, 140, 1000, 860);				elm_grid_pack(vc->fdb_grid, vc->fdg_indoor_button, 333, 0, 333, 140);				elm_grid_pack(vc->fdb_grid, vc->fdg_indoor_box, 0, 140, 1000, 860);				elm_grid_pack(vc->fdb_grid, vc->fdg_icon_button, 666, 0, 333, 140);				elm_grid_pack(vc->fdb_grid, vc->fdg_icon_box, 0, 140, 1000, 860);				evas_object_show(vc->fdb_grid);
			}
			elm_box_pack_end(vc->finedust_box, vc->fdb_grid);
			evas_object_show(vc->finedust_box);
		}
		if (!vc->fdv_next_button) {
			vc->fdv_next_button = elm_button_add(vc->finedust_grid);
		}
		if (vc->fdv_next_button) {
			evas_object_size_hint_align_set(vc->fdv_next_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->fdv_next_button, 1.0, 1.0);			elm_object_text_set(vc->fdv_next_button,_UIB_LOCALE("책상상태"));
			elm_object_style_set(vc->fdv_next_button,"bottom");
			evas_object_show(vc->fdv_next_button);
		}
		elm_grid_pack(vc->finedust_grid, vc->fdv_previous_button, 100, 100, 800, 80);		elm_grid_pack(vc->finedust_grid, vc->finedust_box, 0, 265, 1000, 435);		elm_grid_pack(vc->finedust_grid, vc->fdv_next_button, 100, 850, 800, 80);		evas_object_show(vc->finedust_grid);
	}
}

